name: CI

on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENSE"
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux-macos:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, freebsd-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: master
    - name: Pull
      run: git pull origin master
    - name: Install Dependencies
      run: |
        if [ "${RUNNER_OS}" == "Linux" ]; then
          sudo apt install -y make build-essential libcurl4 libcurl4-openssl-dev
        elif [ "${RUNNER_OS}" == "macOS" ]; then
          brew update
          brew uninstall curl
          brew install curl-openssl
        fi 
    - name: Compile Library and Example
      run: |
        make && make example
  build-freebsd:
    runs-on: ubuntu-latest
    name: A job to run test in FreeBSD
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg update && pkg upgrade
          pkg install -y curl
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: master
    - name: Pull
      run: git pull origin master
    - name: Install Dependencies
      run: |
        pkg update && pkg upgrade
        pkg install -y curl
    - name: Compile Library and Example
      run: |
        make && make example