name: Release

on:
  push:
    tags:
    - "v*"

env:
    GH_TOKEN: ${{ github.token }}

jobs:
  build_and_upload:
    strategy:
      matrix:
        platform:
          - linux/arm64/v8
          - linux/amd64
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
      - name: Pull
        run: git pull origin master
      - name: Install Dependencies
        run: |
          if [ "${RUNNER_OS}" == "Linux" ]; then
            sudo apt install -y make build-essential libcurl4 libcurl4-openssl-dev
          elif [ "${RUNNER_OS}" == "macOS" ]; then
            brew update
            brew uninstall curl
            brew install curl-openssl
          fi
      - name: Compile Shared Object
        run: make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: |
            libgithub.*
            github.h
          